name: lg_city_historic_engine
description: "LG City Historic Engine"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartssh2: ^2.2.0
  shared_preferences: ^2.2.0
  sqflite: ^2.3.3
  path: ^1.9.0
  image: ^4.5.4
  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

# Genera los iconos con: dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/KMLs/logo.png"
  min_sdk_android: 21
  # Si tu logo.png tiene fondo transparente y quieres que Android le ponga
  # un fondo de color sólido detrás en vez de dejarlo transparente,
  # descomenta y ajusta esta línea:
  # adaptive_icon_background: "#0B1220"
  # adaptive_icon_foreground: "assets/images/KMLs/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/KMLs/logos.png
    - assets/images/KMLs/placemark_base.png
    - assets/images_points_of_interest/
    - assets/images_churches_cathedrals/
    - assets/images_museums/
    - assets/images_historical_events/