import 'package:flutter/material.dart';
import 'screens/pag_splash.dart';

final ValueNotifier<ThemeMode> themeNotifier = ValueNotifier(ThemeMode.light);
final ValueNotifier<String> languageNotifier = ValueNotifier('en');

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<ThemeMode>(
      valueListenable: themeNotifier,
      builder: (_, mode, __) {
        return ValueListenableBuilder<String>(
          valueListenable: languageNotifier,
          builder: (_, lang, __) {
            return MaterialApp(
              debugShowCheckedModeBanner: false,
              themeMode: mode,
              theme: ThemeData(
                useMaterial3: true,
                brightness: Brightness.light,
                colorSchemeSeed: const Color(0xFF8B7355),
              ),
              darkTheme: ThemeData(
                useMaterial3: true,
                brightness: Brightness.dark,
                scaffoldBackgroundColor: const Color(0xFF1B1811),
                colorScheme: ColorScheme.fromSeed(
                  seedColor: const Color(0xFF8B7355),
                  brightness: Brightness.dark,
                  surface: const Color(0xFF26221A),
                  onSurface: Colors.white,
                ),
              ),
              home: const SplashPage(),
            );
          },
        );
      },
    );
  }
}

class T {
  static final Map<String, Map<String, String>> _data = {
    'en': {
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'light': 'Light',
      'dark': 'Dark',
      'poi': 'Points of Interest',
      'poi_subtitle': 'Discover historic landmarks and monuments across Lleida',
      'cathedrals': 'Cathedrals & Churches',
      'cathedrals_subtitle':
          'Explore sacred architecture and religious heritage',
      'museums': 'Museums',
      'museums_subtitle': 'Visit cultural institutions and exhibition spaces',
      'events': 'Historical Events',
      'events_subtitle': 'Significant moments in Lleida history',
      'categories': 'Categories',
      'search': 'Search locations...',
      'show_all': 'Show all',
      'send_lg': 'SEND TO LG',
      'details': 'Open details',
      'available': 'locations available',
      'events_available': 'events available',
      'history_details': 'History details',
      'search_events': 'Search events...',
      'help': 'Help',
      'about': 'About',
      'connect': 'Connect',
      'tools': 'Tools',
      'home': 'Home',
      'no_results_found': 'No results found',
      'ai_narration': 'AI Narration',
      'orbit': 'Orbit',
      'executed_successfully': 'executed successfully',
      'error_executing': 'Error executing',
      'relaunch_lg': 'Relaunch LG',
      'shutdown_lg': 'Shutdown LG',
      'reboot_lg': 'Reboot LG',
      'clean_kmls': 'Clean KMLs',
      'clean_logos': 'Clean Logos',
      'show_hide_logos': 'Show/Hide Logos',
      'execute_relaunch_lg': 'Execute Relaunch LG',
      'execute_shutdown_lg': 'Execute Shutdown LG',
      'execute_reboot_lg': 'Execute Reboot LG',
      'execute_clean_kmls': 'Execute Clean KMLs',
      'execute_clean_logos': 'Execute Clean Logos',
      'execute_show_hide': 'Execute Show/Hide',
      'connection': 'Connection',
      'connected_to': 'Connected to',
      'disconnect': 'Disconnect',
      'user_lg': 'User LG',
      'password_lg': 'Password LG',
      'ip_label': 'IP',
      'port_lg': 'Port LG',
      'password_admin': 'Password Admin',
      'screens': 'Screens',
      'connect_lg_button': 'Connect to Liquid Galaxy',
      'connect_success': 'Connected successfully! Saved settings.',
      'connect_failed': 'Connection failed. Check your settings.',
    },
    'es': {
      'settings': 'Ajustes',
      'theme': 'Tema',
      'language': 'Idioma',
      'light': 'Claro',
      'dark': 'Oscuro',
      'poi': 'Puntos de Interés',
      'poi_subtitle': 'Descubre monumentos y lugares históricos en Lleida',
      'cathedrals': 'Catedrales e Iglesias',
      'cathedrals_subtitle':
          'Explora la arquitectura sagrada y el patrimonio religioso',
      'museums': 'Museos',
      'museums_subtitle':
          'Visita instituciones culturales y espacios de exposición',
      'events': 'Eventos Históricos',
      'events_subtitle': 'Momentos significativos de la historia de Lleida',
      'categories': 'Categorías',
      'search': 'Buscar ubicaciones...',
      'show_all': 'Mostrar todo',
      'send_lg': 'ENVIAR A LG',
      'details': 'Ver detalles',
      'available': 'ubicaciones disponibles',
      'events_available': 'eventos disponibles',
      'history_details': 'Detalles históricos',
      'search_events': 'Buscar eventos...',
      'help': 'Ayuda',
      'about': 'Acerca de',
      'connect': 'Conectar',
      'tools': 'Herramientas',
      'home': 'Inicio',
      'no_results_found': 'No se encontraron resultados',
      'ai_narration': 'Narración IA',
      'orbit': 'Órbita',
      'executed_successfully': 'ejecutado correctamente',
      'error_executing': 'Error al ejecutar',
      'relaunch_lg': 'Reiniciar LG',
      'shutdown_lg': 'Apagar LG',
      'reboot_lg': 'Reiniciar LG',
      'clean_kmls': 'Limpiar KMLs',
      'clean_logos': 'Limpiar Logos',
      'show_hide_logos': 'Mostrar/Ocultar Logos',
      'execute_relaunch_lg': 'Ejecutar Reinicio LG',
      'execute_shutdown_lg': 'Ejecutar Apagado LG',
      'execute_reboot_lg': 'Ejecutar Reinicio LG',
      'execute_clean_kmls': 'Ejecutar Limpiar KMLs',
      'execute_clean_logos': 'Ejecutar Limpiar Logos',
      'execute_show_hide': 'Ejecutar Mostrar/Ocultar',
      'connection': 'Conexión',
      'connected_to': 'Conectado a',
      'disconnect': 'Desconectar',
      'user_lg': 'Usuario LG',
      'password_lg': 'Contraseña LG',
      'ip_label': 'IP',
      'port_lg': 'Puerto LG',
      'password_admin': 'Contraseña Admin',
      'screens': 'Pantallas',
      'connect_lg_button': 'Conectar a Liquid Galaxy',
      'connect_success': '¡Conectado correctamente! Ajustes guardados.',
      'connect_failed': 'Conexión fallida. Comprueba tus ajustes.',
    },
    'ca': {
      'settings': 'Ajustos',
      'theme': 'Tema',
      'language': 'Idioma',
      'light': 'Clar',
      'dark': 'Fosc',
      'poi': 'Punts d\'Interès',
      'poi_subtitle': 'Descobreix monuments i llocs històrics a Lleida',
      'cathedrals': 'Catedrals i Esglésies',
      'cathedrals_subtitle':
          'Explora l\'arquitectura sagrada i el patrimoni religiós',
      'museums': 'Museus',
      'museums_subtitle': 'Visita institucions culturals i espais d\'exposició',
      'events': 'Esdeveniments Històrics',
      'events_subtitle': 'Moments significatius de la història de Lleida',
      'categories': 'Categories',
      'search': 'Cercar ubicacions...',
      'show_all': 'Mostrar-ho tot',
      'send_lg': 'ENVIAR A LG',
      'details': 'Veure detalls',
      'available': 'ubicacions disponibles',
      'events_available': 'esdeveniments disponibles',
      'history_details': 'Detalls històrics',
      'search_events': 'Cercar esdeveniments...',
      'help': 'Ajuda',
      'about': 'Quant a',
      'connect': 'Connectar',
      'tools': 'Eines',
      'home': 'Inici',
      'no_results_found': 'No s\'han trobat resultats',
      'ai_narration': 'Narració IA',
      'orbit': 'Òrbita',
      'executed_successfully': 'executat correctament',
      'error_executing': 'Error en executar',
      'relaunch_lg': 'Reiniciar LG',
      'shutdown_lg': 'Apagar LG',
      'reboot_lg': 'Reiniciar LG',
      'clean_kmls': 'Netejar KMLs',
      'clean_logos': 'Netejar Logos',
      'show_hide_logos': 'Mostrar/Ocultar Logos',
      'execute_relaunch_lg': 'Executar Reinici LG',
      'execute_shutdown_lg': 'Executar Apagat LG',
      'reboot_lg': 'Reiniciar LG',
      'execute_reboot_lg': 'Executar Reinici LG',
      'clean_kmls': 'Netejar KMLs',
      'execute_clean_kmls': 'Executar Netejar KMLs',
      'clean_logos': 'Netejar Logos',
      'execute_clean_logos': 'Executar Netejar Logos',
      'show_hide_logos': 'Mostrar/Ocultar Logos',
      'execute_show_hide': 'Executar Mostrar/Ocultar',
      'connection': 'Connexió',
      'connected_to': 'Connectat a',
      'disconnect': 'Desconnectar',
      'user_lg': 'Usuari LG',
      'password_lg': 'Contrasenya LG',
      'ip_label': 'IP',
      'port_lg': 'Port LG',
      'password_admin': 'Contrasenya Admin',
      'screens': 'Pantallas',
      'connect_lg_button': 'Connectar a Liquid Galaxy',
      'connect_success': 'Connectat correctament! Ajustos guardats.',
      'connect_failed': 'Connexió fallida. Comprova els ajustos.',
    },
    'tr': {
      'settings': 'Ayarlar',
      'theme': 'Tema',
      'language': 'Dil',
      'light': 'Aydınlık',
      'dark': 'Karanlık',
      'poi': 'İlgi Çekici Yerler',
      'poi_subtitle': 'Lleida\'daki tarihi yapıları yand anıtları keşfedin',
      'cathedrals': 'Katedraller ve Kiliseler',
      'cathedrals_subtitle': 'Kutsal mimariyi ve dini mirası keşfedin',
      'museums': 'Müzeler',
      'museums_subtitle': 'Kültürel kurumları ve sergi alanlarını ziyaret edin',
      'events': 'Tarihi Olaylar',
      'events_subtitle': 'Lleida tarihindeki önemli anlar',
      'categories': 'Categoriler',
      'search': 'Konum ara...',
      'show_all': 'Hepsini göster',
      'send_lg': 'LG\'YE GÖNDER',
      'details': 'Detayları aç',
      'available': 'konum mevcut',
      'events_available': 'etkinlik mevcut',
      'history_details': 'Tarih detayları',
      'search_events': 'Etkinlik ara...',
      'help': 'Yardım',
      'about': 'Hakkında',
      'connect': 'Bağlan',
      'tools': 'Araçlar',
      'home': 'Ana Sayfa',
      'no_results_found': 'Sonuç bulunamadı',
      'ai_narration': 'AI Anlatımı',
      'orbit': 'Yörünge',
      'executed_successfully': 'başarıyla çalıştırıldı',
      'error_executing': 'Çalıştırırken hata oluştu:',
      'relaunch_lg': 'LG Yeniden Başlat',
      'shutdown_lg': 'LG Kapat',
      'reboot_lg': 'LG Yeniden Başlat',
      'clean_kmls': 'KML Temizle',
      'clean_logos': 'Logoları Temizle',
      'show_hide_logos': 'Logoları Göster/Gizle',
      'execute_relaunch_lg': 'LG Yeniden Başlatmayı Çalıştır',
      'execute_shutdown_lg': 'LG Kapatmayı Çalıştır',
      'execute_reboot_lg': 'LG Yeniden Başlatmayı Çalıştır',
      'execute_clean_kmls': 'KML Temizlemeyi Çalıştır',
      'execute_clean_logos': 'Logoları Temizlemeyi Çalıştır',
      'execute_show_hide': 'Göster/Gizleyi Çalıştır',
      'connection': 'Bağlantı',
      'connected_to': 'Bağlandı',
      'disconnect': 'Bağlantıyı kes',
      'user_lg': 'LG Kullanıcısı',
      'password_lg': 'LG Şifresi',
      'ip_label': 'IP',
      'port_lg': 'LG Portu',
      'password_admin': 'Admin Şifresi',
      'screens': 'Ekranlar',
      'connect_lg_button': 'Liquid Galaxy\'ye Bağlan',
      'connect_success': 'Başarıyla bağlandı! Ayarlar kaydedildi.',
      'connect_failed': 'Bağlantı başarısız. Ayarlarınızı kontrol edin.',
    },
  };

  static String s(String key) {
    return _data[languageNotifier.value]?[key] ?? _data['en']![key] ?? key;
  }
}
